extension Generator {
    
    func assembleInitialComments(_ fileName: String) -> String {
        
        return """
        // \(fileName).swift
        // Auto-generated by SwiftLex
        // See https://github.com/Fleli/SwiftLex
        """
        
    }
    
}
